name: webMethods MSR CI/CD (VM deployment)

on:
  workflow_dispatch:

jobs:
  install-packages:
    runs-on: msr-vm
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install packages
      run: |
        for WM_PACKAGE in $(cat packages); do
          /opt/softwareag/wpm/bin/wpm.sh update \
            -u ${{ secrets.GIT_USERNAME }} \
            -p ${{ secrets.GIT_PAT }} \
            -r ${{ vars.GIT_URL }} \
            -d ${{ vars.WM_PATH }} \
            $WM_PACKAGE
        done

    - name: Copy application.properties
      run: |
        cp application.properties ${{ vars.WM_PATH }}/application.properties 

    - name: Stop and start the MSR
      run: |
        ${{ vars.WM_PATH }}/bin/shutdown.sh
        ${{ vars.WM_PATH }}/bin/startup.sh