name: webMethods MSR CI/CD (VM deployment)

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: msr-vm
    steps:
    - name: Set Node.js version to use
      run: |
        nvm use 14

    - name: Check out repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

